version: '3'

services:

# Database
  hydro-postgres:
    image: "postgres:12.2"
    restart: always
    container_name: "kazhydromet-postgres"
    env_file: .local_env
    volumes:
      - /docker_volumes/local_dev/kazhydromet/pgdata:/var/lib/postgresql/data
    ports:
      - "2424:5432"
