hydrostation_categories = [
    {
        "pk": "ГП-1",
        "name": "Речной пост 1 разряд"
    },
    {
        "pk": "ГП-2",
        "name": "Речной пост 2 разряд"
    },
    {
        "pk": "ГП-3",
        "name": "Речной пост 3 разряд"
    },
    {
        "pk": "МГП-1",
        "name": "Морской пост 1 разряд"
    },
    {
        "pk": "МГП-2",
        "name": "Морской пост 2 разряд"
    },
    {
        "pk": "МГП-3",
        "name": "Морской пост 3 разряд"
    },
    {
        "pk": "МС",
        "name": "Гидрометеорологические станции (Мангистауский ЦГМ)"
    },
    {
        "pk": "ОГП-1",
        "name": "Озерный пост 1 разряд"
    },
    {
        "pk": "ОГП-2",
        "name": "Озерный пост 2 разряд"
    },
]


hydrostations = [
{'category': 'ГП-1',
  'lat': '48.00',
  'lon': '85.22',
  'name': 'Р.Кара Ертис – пос. Боран',
  'nameEn': 'r. Kara Ertis - pos. Boran',
  'pk': 11001,
  'region': 'KZ-VOS'},
 {'category': 'ГП-2',
  'lat': '50.39',
  'lon': '81.00',
  'name': 'Р. Ертис– с. Баженово',
  'nameEn': 'r. Ertis - s. Bazhenovo',
  'pk': 11002,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '48.02',
  'lon': '85.43',
  'name': 'Р. Кара Ертис – 7.5 км ниже границы с КНР',
  'nameEn': 'r. Kara ertis - 7.5 km nizhe granicy s KNR',
  'pk': 11003,
  'region': 'KZ-VOS'},
 {'category': 'ГП-2',
  'lat': '49.89',
  'lon': '82.70',
  'name': 'Р. Ертис – с. Аблайкит',
  'nameEn': 'r. Ertis - s. Abylaikit',
  'pk': 11019,
  'region': 'KZ-VOS'},
 {'category': 'ГП-2',
  'lat': '50.38',
  'lon': '80.26',
  'name': 'Р. Ертис – г. Семей',
  'nameEn': 'r. Ertis - g. Semey',
  'pk': 11025,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '50.89',
  'lon': '78.31',
  'name': 'Р. Ертис – с. Семиярка',
  'nameEn': 'r. Ertis - s. Semiyarka',
  'pk': 11027,
  'region': 'KZ-VOS'},
 {'category': 'ГП-3',
  'lat': '52.26',
  'lon': '76.94',
  'name': 'Р. Ертис – г. Павлодар (затон)',
  'nameEn': 'r. Yertis – g. Pavlodar (zaton)',
  'pk': 11037,
  'region': 'KZ-PAV'},
 {'category': 'ГП-2',
  'lat': '53.34',
  'lon': '75.47',
  'name': 'Р. Ертис – п. Ертис',
  'nameEn': 'r. Ertis p. Ertis',
  'pk': 11040,
  'region': 'KZ-PAV'},
 {'category': 'ГП-1',
  'lat': '53.70',
  'lon': '75.08',
  'name': 'Р.Ертис – с. Прииртышское',
  'nameEn': 'r.Yertis – s. Priirtyshskoye',
  'pk': 11041,
  'region': 'KZ-PAV'},
 {'category': 'ГП-1',
  'lat': '48.43',
  'lon': '85.84',
  'name': 'Р. Бас-Теректы – с. Мойылды (Николаевка)',
  'nameEn': 'r. Bas-Terekty - s. Moyilldy',
  'pk': 11063,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '48.13',
  'lon': '85.20',
  'name': 'Р. Калжыр – с.Калжыр',
  'nameEn': 'r. Kalzhyr - s. Kalzhyr',
  'pk': 11068,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '47.28',
  'lon': '84.11',
  'name': 'Р. Кандысу – с.Сарыолен',
  'nameEn': 'r. Kandysu - s. Saryolen',
  'pk': 11077,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.01',
  'lon': '82.79',
  'name': 'Р. Улкен Буконь – с. Джумба',
  'nameEn': 'r. Ulken Bukon - s. Dzhumba',
  'pk': 11094,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '48.61',
  'lon': '83.87',
  'name': 'Р. Куршим – с. Вознесенка',
  'nameEn': 'r. Kurshim - s. Voznesenka',
  'pk': 11108,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.21',
  'lon': '84.52',
  'name': 'Р. Нарын– с.Улькен Нарын',
  'nameEn': 'r. Naryn - s. Ulken Natyn',
  'pk': 11117,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.37',
  'lon': '86.45',
  'name': 'Р.Буктырма – с. Берель  ',
  'nameEn': 'r. Buktyrma - s. Berel',
  'pk': 11124,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.33',
  'lon': '85.17',
  'name': 'Р. Буктырма –с.Барлык',
  'nameEn': 'r. Buktyrma - s. Barlyk',
  'pk': 11126,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.83',
  'lon': '84.33',
  'name': 'Р. Буктырма – с. Лесная пристань',
  'nameEn': 'r. Buktyrma s. Lesnaya pristan',
  'pk': 11129,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.38',
  'lon': '85.41',
  'name': 'Р.Аксу – с. Аксу  ',
  'nameEn': 'r. Aksu - s Aksu',
  'pk': 11143,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.51',
  'lon': '84.39',
  'name': 'Р. Лев. Березовка – с. Средигорное',
  'nameEn': 'r. Lev.Berezovka - s. Sredigornoye',
  'pk': 11146,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.89',
  'lon': '84.08',
  'name': 'Р. Тургысын – с. Кутиха',
  'nameEn': 'r. Turgysyn - s. Kutiha',
  'pk': 11147,
  'region': 'KZ-VOS'},
 {'category': 'ГП-2',
  'lat': '49.39',
  'lon': '82.56',
  'name': 'Р. Сибе – с. Алгабас ',
  'nameEn': 'r. Sibe - s. Algabas',
  'pk': 11160,
  'region': 'KZ-VOS'},
 {'category': 'ГП-2',
  'lat': '50.28',
  'lon': '83.38',
  'name': 'Р. Ульби – г.Риддер',
  'nameEn': 'r. Ulbi - g. Ridder',
  'pk': 11163,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '50.01',
  'lon': '82.84',
  'name': 'Р. Ульби – с. Ульби Перевалочная',
  'nameEn': 'r. Ulbi - s. Ulbi Perevalochnaya',
  'pk': 11164,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '50.19',
  'lon': '82.58',
  'name': 'Р. Глубочанка - с.Белокаменка',
  'nameEn': 'r. Glubochanka - s. Belokamenka',
  'pk': 11170,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.99',
  'lon': '82.26',
  'name': 'Р.Дресвянка – с. Отрадное  ',
  'nameEn': 'r. Dresvyanka - s. Otradnoe',
  'pk': 11187,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '50.25',
  'lon': '82.24',
  'name': 'Р. Красноярка – с. Предгорное',
  'nameEn': 'r. Krasnoyarka - s. Predgornoye',
  'pk': 11188,
  'region': 'KZ-VOS'},
 {'category': 'ГП-2',
  'lat': '49.99',
  'lon': '82.92',
  'name': 'Р.Киши Ульби- с.Горная Ульбинка',
  'nameEn': 'r. Kyshy Ulbi - s. Gornaya Ulbinka',
  'pk': 11189,
  'region': 'KZ-VOS'},
 {'category': 'ГП-2',
  'lat': '50.49',
  'lon': '82.41',
  'name': 'Р. Оба – с.Верхуба (вместо с.Каракожа)',
  'nameEn': 'r. Oba - s. Verhuba (vmesto s. Karakozha)',
  'pk': 11203,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '50.61',
  'lon': '81.88',
  'name': 'Р. Оба – с. Шемонаиха',
  'nameEn': 'r. Oba - s. Shemonaiha',
  'pk': 11207,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '49.16',
  'lon': '81.97',
  'name': 'Р. Шар – аул Кентарлау (с.Николаевка) ',
  'nameEn': 'r. Shar - aul Kentarlau (s. Nikolaevka)',
  'pk': 11233,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '51.74',
  'lon': '72.31',
  'name': 'Р. Силеты – Новомарковка',
  'nameEn': 'r. Silety - Novomarkovka',
  'pk': 11242,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '52.00',
  'lon': '72.69',
  'name': 'Р. Силеты – Бестогай',
  'nameEn': 'r. Silety - Bestogay',
  'pk': 11253,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '51.54',
  'lon': '71.94',
  'name': 'Р. Силеты – с. Приречное ',
  'nameEn': 'r. Silety - s. Prirechnoe',
  'pk': 11272,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '52.49',
  'lon': '73.29',
  'name': 'Р. Силеты – свх. Изобильное',
  'nameEn': 'r. Silety - svh. Izobilnoe',
  'pk': 11275,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '53.10',
  'lon': '69.01',
  'name': 'Р. Шагалалы – с. Павловка',
  'nameEn': 'r. Shagalaly - s. Pavlovka',
  'pk': 11291,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '53.69',
  'lon': '69.62',
  'name': 'Шағалалы ө. – Северное с.',
  'nameEn': 'r. Shagalaly – s. Severnoye',
  'pk': 11293,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '50.62',
  'lon': '73.03',
  'name': 'р. Есиль – с. Приишимское                    ',
  'nameEn': 'r. Yesil – s. Priishimskoye',
  'pk': 11395,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '50.75',
  'lon': '72.34',
  'name': 'Р. Есиль– с. Турген(с.Тургеневка)',
  'nameEn': 'r. Esil - s. Turgen',
  'pk': 11397,
  'region': 'KZ-AKM'},
 {'category': 'ГП-2',
  'lat': '51.16',
  'lon': '71.41',
  'name': 'р. Есиль - г.Астана',
  'nameEn': 'r. Esil - g. Astana',
  'pk': 11398,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '51.09',
  'lon': '66.32',
  'name': 'Р.Есиль – с. Державинск',
  'nameEn': 'r. Esil - s. Derzhavinsk',
  'pk': 11402,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '52.02',
  'lon': '66.27',
  'name': 'Р.Есиль – с. Каменный карьер ',
  'nameEn': 'r. Esil - s. Kamennyi karier',
  'pk': 11404,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '52.96',
  'lon': '66.63',
  'name': 'р. Есиль – с. Токсан би',
  'nameEn': 'r. Esil - s. Toxan bi',
  'pk': 11405,
  'region': 'KZ-SEV'},
 {'category': 'ОГП-2',
  'lat': '53.87',
  'lon': '67.43',
  'name': 'вдхр. Сергеевское (р. Есиль) – г. Сергеевка (ГЭС)',
  'nameEn': 'vdkhr. Sergeyevskoye (r. Yesil) – g. Sergeyevka (GES)',
  'pk': 11407,
  'region': 'KZ-SEV'},
 {'category': 'ГП-2',
  'lat': '52.88',
  'lon': '67.43',
  'name': 'р. Есиль – г. Сергеевка ',
  'nameEn': 'r. Yesil – g. Sergeyevka',
  'pk': 11408,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '54.29',
  'lon': '68.33',
  'name': 'р. Есиль – выше с. Покровка с.',
  'nameEn': 'r. Yesil – vyshe s. Pokrovka ',
  'pk': 11409,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '54.91',
  'lon': '69.13',
  'name': 'р. Есиль – Петропавл қ.',
  'nameEn': 'r. Yesil – g.Petropavlovsk',
  'pk': 11410,
  'region': 'KZ-SEV'},
 {'category': 'ГП-2',
  'lat': '51.10',
  'lon': '71.49',
  'name': 'р. Есиль - с.Тельман',
  'nameEn': 'r. Esil - s. Telman',
  'pk': 11411,
  'region': 'KZ-AKM'},
 {'category': 'ГП-2',
  'lat': '51.16',
  'lon': '71.42',
  'name': 'р.Есиль - пеш.мост Астана',
  'nameEn': 'r. Esil - pesh.most Astana',
  'pk': 11412,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '51.17',
  'lon': '71.34',
  'name': 'р. Есиль – с. Коктал',
  'nameEn': 'r. Esil - s. Koktal',
  'pk': 11413,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '51.31',
  'lon': '70.73',
  'name': 'Р.Есиль – п.Новоишимка',
  'nameEn': 'r. Esil - p. Novoishimka',
  'pk': 11414,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '51.09',
  'lon': '72.44',
  'name': 'Р. Мойылды – с. Николаевка ',
  'nameEn': 'r. Moyildy -s. Nikolaevka',
  'pk': 11421,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '51.79',
  'lon': '69.46',
  'name': 'Р. Калкутан – с. Калкутан',
  'nameEn': 'r. Kalkutan - s. Kalkutan',
  'pk': 11424,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '52.54',
  'lon': '68.79',
  'name': 'Р. Жабай – с. Балкашино',
  'nameEn': 'r. Zhabai - s. Balkashino',
  'pk': 11432,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '51.80',
  'lon': '68.37',
  'name': 'Р. Жабай – г. Атбасар',
  'nameEn': 'r. Zhabai - g. Atbasar',
  'pk': 11433,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '52.74',
  'lon': '67.66',
  'name': 'Бабықбұрлық ө. – Гусаковка с.',
  'nameEn': 'r. Babakbyrlyk - s. Gusakovka ',
  'pk': 11453,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '53.66',
  'lon': '67.41',
  'name': 'р. Иманбурлык – с. Соколовка',
  'nameEn': 'r. Imanburlyk – s. Sokolovka',
  'pk': 11461,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '52.58',
  'lon': '67.68',
  'name': 'р. Акканбурлык- с. Ковыльное (с. Привольное)',
  'nameEn': 'r. Akkanburlyk- s. Kovylnoye (s. Privolnoye)',
  'pk': 11468,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '52.79',
  'lon': '66.76',
  'name': 'Аққанбұрлық ө. - Возвышенка с.',
  'nameEn': 'r. Akkanbyrlyk - s.Vozvyshenka ',
  'pk': 11469,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '51.02',
  'lon': '71.98',
  'name': 'Р. Есиль – с. Волгодоновка',
  'nameEn': 'r. Esil - s. Volgodonovka',
  'pk': 11644,
  'region': 'KZ-AKM'},
 {'category': 'ГП-2',
  'lat': '54.52',
  'lon': '68.72',
  'name': 'р. Есиль – с. Новоникольское ',
  'nameEn': 'r. Yesil – s. Novonikolskoye',
  'pk': 11645,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '55.32',
  'lon': '69.45',
  'name': 'р. Есиль - Долматово с.',
  'nameEn': 'r. Yesil - s. Dolmatovo',
  'pk': 11646,
  'region': 'KZ-SEV'},
 {'category': 'ГП-1',
  'lat': '49.83',
  'lon': '82.65',
  'name': 'Р. Абылайкит – с. Самсоновка',
  'nameEn': 'r. Abylaykit - s. Samsonovka',
  'pk': 11661,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '50.26',
  'lon': '75.60',
  'name': 'Р. Ертис –  свх. Бобровский (а.Жанабет)',
  'nameEn': 'r. Yertis – svkh. Bobrovskiy (a.Zhanabet)',
  'pk': 11663,
  'region': 'KZ-PAV'},
 {'category': 'ГП-1',
  'lat': '52.33',
  'lon': '76.88',
  'name': 'р. Ертис – г. Павлодар (мост) ',
  'nameEn': 'r. Ertis - Pavlodar (most)',
  'pk': 11667,
  'region': 'KZ-PAV'},
 {'category': 'ГП-1',
  'lat': '49.98',
  'lon': '82.42',
  'name': 'Р. Уланка – п. Герасимовка',
  'nameEn': 'r. Ulanka - p. Gerasimovka',
  'pk': 11668,
  'region': 'KZ-VOS'},
 {'category': 'ОГП-2',
  'lat': '48.79',
  'lon': '86.02',
  'name': 'Оз. Маркаколь – с. Уранхай',
  'nameEn': 'oz. Markakol - s. Uranhay',
  'pk': 11900,
  'region': 'KZ-VOS'},
 {'category': 'ОГП-2',
  'lat': '52.15',
  'lon': '72.74',
  'name': 'Селетинское вдхр. - с. Силеты',
  'nameEn': 'Seletinskoe vdhr. - s. Silety',
  'pk': 11915,
  'region': 'KZ-AKM'},
 {'category': 'ОГП-2',
  'lat': '54.00',
  'lon': '68.40',
  'name': 'Үлкен Тарангул көлі – Корнеевка с.',
  'nameEn': 'Alken Tarangul Kuli - s. Korneevka ',
  'pk': 11916,
  'region': 'KZ-SEV'},
 {'category': 'ОГП-2',
  'lat': '53.30',
  'lon': '69.38',
  'name': 'Оз. Копа – г. Кокшетау',
  'nameEn': 'Oz. Kopa - g. Kokshetau',
  'pk': 11919,
  'region': 'KZ-AKM'},
 {'category': 'ОГП-2',
  'lat': '50.78',
  'lon': '75.71',
  'name': 'Оз.Сабындыколь – п. Баянауыл  ',
  'nameEn': 'Oz.Sabyndykol - p. Bayanaul',
  'pk': 11935,
  'region': 'KZ-PAV'},
 {'category': 'ГП-1',
  'lat': '51.44',
  'lon': '61.33',
  'name': 'р.Тобол – с.Аккарга',
  'nameEn': 'r.Tobol – s.Akkarga',
  'pk': 12001,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '52.39',
  'lon': '61.70',
  'name': 'р.Тобол – с. Гришенка',
  'nameEn': 'r.Tobol – s. Grishenka',
  'pk': 12002,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '53.21',
  'lon': '63.65',
  'name': 'р.Тобол – г. Костанай',
  'nameEn': 'r.Tobol – g. Kostanay',
  'pk': 12008,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '54.10',
  'lon': '63.84',
  'name': 'р.Тобол – с.Милютинка',
  'nameEn': 'r.Tobol – s.Milyutinka',
  'pk': 12009,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '52.37',
  'lon': '61.11',
  'name': 'р.Желкуар – п.Чайковское',
  'nameEn': 'r.Zhelkuar – p.Chaykovskoye',
  'pk': 12031,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '53.78',
  'lon': '62.18',
  'name': 'р.Аят – с.Варваринка',
  'nameEn': 'r.Ayat – s.Varvarinka',
  'pk': 12032,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '53.78',
  'lon': '62.18',
  'name': 'р.Тогызак – ст. Тогузак',
  'nameEn': 'r.Togyzak – st. Toguzak',
  'pk': 12072,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '53.92',
  'lon': '64.75',
  'name': 'р.Убаган – с.Аксуат',
  'nameEn': 'r. Ubagan - s.Aksuat',
  'pk': 12075,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '52.90',
  'lon': '61.53',
  'name': 'р.Камыстыаят – п.Свердловка',
  'nameEn': 'r.Kamystyayat – p.Sverdlovka',
  'pk': 12564,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '54.20',
  'lon': '63.46',
  'name': 'р.Уй – с.Уйское',
  'nameEn': 'r.Uy – s.Uyskoye',
  'pk': 12701,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '49.20',
  'lon': '63.12',
  'name': 'р.Торгай – пески Тусум',
  'nameEn': 'r.Torgay – peski Tusum',
  'pk': 13002,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '50.10',
  'lon': '65.32',
  'name': 'р.Каратургай – п.Урпек',
  'nameEn': 'r.Karaturgay - p. Urpek',
  'pk': 13005,
  'region': 'KZ-KUS'},
 {'category': 'ГП-3',
  'lat': '49.94',
  'lon': '60.13',
  'name': 'Р.Иргиз-с.Карабутак',
  'nameEn': 'r. Irgiz - s.Karabutak',
  'pk': 13035,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '48.71',
  'lon': '60.30',
  'name': 'Р.Иргиз-с.Шенбертал',
  'nameEn': 'r. Irgiz - s. Shenbertal',
  'pk': 13038,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '48.38',
  'lon': '67.85',
  'name': 'р. Кара –Кенгир –с. Малшыбай             ',
  'nameEn': 'r. Kara –Kengir –s. Malshybay',
  'pk': 13048,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '49.34',
  'lon': '74.47',
  'name': 'р. Нура – с. Бесоба',
  'nameEn': 'r. Nura – s. Besoba',
  'pk': 13061,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '49.97',
  'lon': '74.05',
  'name': 'р. Нура – с. Шешенкара',
  'nameEn': 'r. Nura – s. Sheshenkara',
  'pk': 13064,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '50.00',
  'lon': '73.23',
  'name': 'р. Нура – ж.д.ст. Балыкты',
  'nameEn': 'r. Nura - zh.d.st. Balykty',
  'pk': 13066,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '50.83',
  'lon': '71.34',
  'name': 'Р. Нура – с. Р.Кошкарбаева (с. Романовка)',
  'nameEn': 'r. Nura - s.R.Koshkarbaeva',
  'pk': 13076,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '50.59',
  'lon': '70.01',
  'name': 'р. Нура - с.Коргалжын ',
  'nameEn': 'r. Nura - s. Korgalzhyn',
  'pk': 13077,
  'region': 'KZ-AKM'},
 {'category': 'ГП-1',
  'lat': '49.11',
  'lon': '73.47',
  'name': 'р. Шерубайнура – с. Шопан                   ',
  'nameEn': 'r. Sherubaynura – s. Shopan',
  'pk': 13090,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '49.24',
  'lon': '72.97',
  'name': 'r. Sherubainur - rzd. Karamuryn       ',
  'nameEn': 'r. Sherubainur - rzd. Karamuryn',
  'pk': 13091,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '49.10',
  'lon': '75.86',
  'name': 'р. Талды – с. Новостройка                     ',
  'nameEn': 'r. Taldy – s. Novostroyka',
  'pk': 13105,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '48.55',
  'lon': '70.44',
  'name': 'р.Сарысу – рзд. 189 км.',
  'nameEn': 'r.Sarysu - rzd. 189 km.',
  'pk': 13115,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '48.31',
  'lon': '69.63',
  'name': 'р. Сарысу – ж.д.ст. Кызылжар               ',
  'nameEn': 'r. Sarysu - zh.d.st. Kyzylzhar',
  'pk': 13116,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '48.67',
  'lon': '71.64',
  'name': 'р. Жаман –Сарысу п. Атасу                   ',
  'nameEn': 'r. Zhaman –Sarysu p. Atasu',
  'pk': 13128,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '49.87',
  'lon': '72.57',
  'name': 'р. Сокур – п. Каражар                             ',
  'nameEn': 'r. Sokur - Karazhar',
  'pk': 13142,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '50.25',
  'lon': '71.57',
  'name': 'р. Улькен – Кундызды – с. Киевка        ',
  'nameEn': 'r. Ulken – Kundyzdy – s. Kiyevka',
  'pk': 13148,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '49.75',
  'lon': '71.72',
  'name': 'р. Нура – с. Акмешит                             ',
  'nameEn': 'r. Nura – s. Akmeshit',
  'pk': 13190,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '49.67',
  'lon': '69.55',
  'name': 'р. Жаман –Кон – п. Баршино                  ',
  'nameEn': 'r. Zhaman –Kon – p. Barshino',
  'pk': 13198,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '51.20',
  'lon': '65.03',
  'name': 'р.Дамды – с.Дамды',
  'nameEn': 'r.Damdy – s.Damdy',
  'pk': 13201,
  'region': 'KZ-KUS'},
 {'category': 'ГП-1',
  'lat': '49.50',
  'lon': '66.13',
  'name': 'р.Сараторгай – п.Екидин',
  'nameEn': 'r.Saratorgay – p.Yekidin',
  'pk': 13221,
  'region': 'KZ-KUS'},
 {'category': 'ОГП-2',
  'lat': '50.48',
  'lon': '69.54',
  'name': 'Оз. Султанкельды – с. Каражар',
  'nameEn': 'Oz. Sultankeldy - s. Karazhar',
  'pk': 13901,
  'region': 'KZ-AKM'},
 {'category': 'ОГП-1',
  'lat': '47.83',
  'lon': '59.61',
  'name': 'Оз.Шалкар-г.Шалкар',
  'nameEn': 'oz. Shalkar - g. Shalkar',
  'pk': 13902,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '45.79',
  'lon': '80.47',
  'name': 'Р. Иле – 8.5 км ниже границы с КНР (Онопко)',
  'nameEn': 'r Ile - 8.5 km nizhe granicy s KNR (ONOPKO)',
  'pk': 14001,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.76',
  'lon': '80.23',
  'name': 'р.  Иле – пр. Добын',
  'nameEn': 'r. Ile - pr.Dobyn',
  'pk': 14002,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.84',
  'lon': '79.01',
  'name': 'Р. Иле – 164 км выше Капчагайской ГЭС',
  'nameEn': 'r. Ile - 164 km vyshe Kapchagaiskoy GES',
  'pk': 14004,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '44.13',
  'lon': '76.98',
  'name': 'Р. Иле -  уроч. Капчагай',
  'nameEn': 'r. Ile - uroch. Kapchagai',
  'pk': 14011,
  'region': 'ALMATY'},
 {'category': 'ГП-2',
  'lat': '44.96',
  'lon': '75.80',
  'name': 'Р. Иле-  с. Ушжарма',
  'nameEn': 'r. Ile- s. Ushzharma',
  'pk': 14014,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '45.07',
  'lon': '75.41',
  'name': 'Р. Иле –1 км ниже ответвления рук. Жидели',
  'nameEn': 'r. Ile - 1 km nizhe otvetvleniya ruk. Zhideli',
  'pk': 14016,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '45.43',
  'lon': '79.33',
  'name': 'Р. Иле – аул Жидели',
  'nameEn': 'r. Ile - aul Zhideli',
  'pk': 14017,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '42.84',
  'lon': '80.06',
  'name': 'Р.Текес – с.Текес',
  'nameEn': 'r. Tekes - s. Tekes',
  'pk': 14022,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '42.60',
  'lon': '80.00',
  'name': 'Р. Баянкол –с. Баянкол',
  'nameEn': 'r. Bayankol - s. Bayankol',
  'pk': 14033,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '44.44',
  'lon': '80.36',
  'name': 'р. Коргас-в 18км выше с. Баскуншы  ',
  'nameEn': 'r. Korgas - v 18 km vyshe s. Baskunshy',
  'pk': 14043,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.47',
  'lon': '79.83',
  'name': 'р. Осек – 1.7 км выше впад. в р. Киши Осек',
  'nameEn': 'r. Osek - 1.7 over vpad. V r. Kishi Osek',
  'pk': 14072,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.46',
  'lon': '79.82',
  'name': 'р. Киши Осек – в 0.2 км выше сл. с р. Осек ',
  'nameEn': 'r. Kishi Osek - 0.2 vyshe sl. S r. Osek',
  'pk': 14078,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '43.50',
  'lon': '79.21',
  'name': 'Р. Шарын – уроч. Сарытогай',
  'nameEn': 'r. Sharyn - uroch. Sarytogai',
  'pk': 14118,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '42.76',
  'lon': '79.17',
  'name': 'Р. Каркара – у выхода из гор',
  'nameEn': 'r. Karkara - u vyhoda iz gor',
  'pk': 14136,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.30',
  'lon': '79.20',
  'name': 'Р. Темирлик – с.Темирлик',
  'nameEn': 'r. Temirlik - s. Temirlik',
  'pk': 14142,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.32',
  'lon': '78.52',
  'name': 'Р. Шилик – выше вдхр. Бартогай',
  'nameEn': 'r. Shilik - vyshe vdhr. Bartogai',
  'pk': 14159,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.44',
  'lon': '78.41',
  'name': 'Р. Шилик – с. Малыбай',
  'nameEn': 'r. Shilik - s.Malybai',
  'pk': 14160,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.34',
  'lon': '77.62',
  'name': 'Р. Турген – с. Таутурген',
  'nameEn': 'r. Turgen - s. Tauturgen',
  'pk': 14187,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.30',
  'lon': '77.50',
  'name': 'Р. Есик – г. Есик',
  'nameEn': 'r. Esik - g. Esik',
  'pk': 14198,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.25',
  'lon': '77.22',
  'name': 'Р. Талгар – г. Талгар',
  'nameEn': 'r. Talgar - g. Talgar',
  'pk': 14200,
  'region': 'ALMATY'},
 {'category': 'ГП-3',
  'lat': '43.13',
  'lon': '76.61',
  'name': 'Р. Каскелен – г. Каскелен',
  'nameEn': 'r. Kaskelen - g. Kaskelen',
  'pk': 14218,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.72',
  'lon': '77.07',
  'name': 'Р.Каскелен - устье',
  'nameEn': 'r. kaskelen - ustye',
  'pk': 14223,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.04',
  'lon': '76.99',
  'name': 'Р. Ул. Алматы – в 1.1 км выше оз.Ульк.Алм.',
  'nameEn': 'r. ul. Almaty - v 1.1 km vyshe oz. Ulken Almaty',
  'pk': 14239,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.11',
  'lon': '76.92',
  'name': 'Р. Ул. Алм.–в 2 км выше устья р. Проходной',
  'nameEn': 'r. Ulken Almaty - v 2 km vyshe utya r. Prohodnoy',
  'pk': 14242,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.08',
  'lon': '76.99',
  'name': 'Р. Кумбель – устье',
  'nameEn': 'r. Kumbel - ustye',
  'pk': 14250,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.11',
  'lon': '76.91',
  'name': 'Р. Проходная – устье',
  'nameEn': 'r. Prohodnaya - ',
  'pk': 14252,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.12',
  'lon': '76.92',
  'name': 'Руч. Тересбутак – устье',
  'nameEn': 'ruch. Teresbutak - ustye',
  'pk': 14253,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.09',
  'lon': '77.08',
  'name': 'Р. Киши Алматы – МС Мынжилки',
  'nameEn': 'r. Kyshy Almaty - MC Mynzhylky',
  'pk': 14254,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.11',
  'lon': '77.08',
  'name': 'Р. Киши Алматы – альпбаза  «Туюксу»',
  'nameEn': 'r. Kyshy Almaty - alpbaza Tuyuksu',
  'pk': 14255,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.14',
  'lon': '77.07',
  'name': 'Р. Киши Алматы – ниже устья р.Сарысай',
  'nameEn': 'r. Kyshy Almaty - nizhe ustya r. Sarysai',
  'pk': 14257,
  'region': 'ALMATY'},
 {'category': 'ГП-3',
  'lat': '43.17',
  'lon': '77.04',
  'name': 'Р. Киши Алматы –  Медеу',
  'nameEn': 'r. Kyshy Almaty - Medeo',
  'pk': 14260,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.19',
  'lon': '76.99',
  'name': 'Р. Киши Алматы – г. Алматы',
  'nameEn': 'r. Kyshy Almaty - g. Almaty',
  'pk': 14262,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.16',
  'lon': '77.04',
  'name': 'Р. Батарейка – д/о «Просвещенец»',
  'nameEn': 'r. Batareika - d/o Prosveshenec',
  'pk': 14276,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.18',
  'lon': '77.05',
  'name': 'Р. Бутак– с. Бутак',
  'nameEn': 'r. Butak - s. Butak',
  'pk': 14277,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.69',
  'lon': '76.31',
  'name': 'Р. Курты – база клх. им. Ленина',
  'nameEn': 'r. Kurty - baza klh. imeni Lenina',
  'pk': 14295,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '45.12',
  'lon': '76.43',
  'name': 'Р. Узын Каргалы – п. Фабричный',
  'nameEn': 'r. Uzyn Kargaly - p. Fabrichnyi',
  'pk': 14324,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '45.01',
  'lon': '75.46',
  'name': 'Р. Иле. пр. Суминка-6 км ниже истока',
  'nameEn': 'r. Ile. pr. Suminka - 6 km nizhe istoka',
  'pk': 14329,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '45.11',
  'lon': '75.31',
  'name': 'Р. Иле. рук. Жидели – 16 км ниже истока',
  'nameEn': 'r. Ile ruk. Zhideli - 16 km nizhe istoka',
  'pk': 14332,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '45.75',
  'lon': '74.25',
  'name': 'Р. Иле. пр. Ир - устье',
  'nameEn': 'r. Ile pr. Ir - ustye',
  'pk': 14334,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '47.51',
  'lon': '72.92',
  'name': 'р. Мойынты – ж.д.ст.Киик                     ',
  'nameEn': 'r. Moyynty – zh.d.st.Kiik',
  'pk': 14343,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '48.32',
  'lon': '75.00',
  'name': 'р. Токырауын – с.Актогай                      ',
  'nameEn': 'r. Tokyrauyn – s.Aktogay',
  'pk': 14349,
  'region': 'KZ-KAR'},
 {'category': 'ГП-1',
  'lat': '47.80',
  'lon': '81.26',
  'name': 'Р. Аягоз – с. Тарбагатай',
  'nameEn': 'r. Ayagoz - s. Tarbagatai',
  'pk': 14368,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '47.94',
  'lon': '80.45',
  'name': 'Р. Аягоз – г. Аягоз',
  'nameEn': 'r. Ayagoz - g. Ayagoz',
  'pk': 14369,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '45.54',
  'lon': '80.56',
  'name': 'р. Лепси –г. Лепси ',
  'nameEn': 'r. Lepsi - g. Lepsi ',
  'pk': 14382,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '46.28',
  'lon': '78.33',
  'name': 'р. Лепси –а. Толебаев ',
  'nameEn': 'r. Lepsi - a. Tolebaev',
  'pk': 14386,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '45.40',
  'lon': '80.11',
  'name': 'р. Баскан-с. Екиаша ',
  'nameEn': 'r. Baskan - s. Ekiasha',
  'pk': 14390,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '45.88',
  'lon': '78.71',
  'name': 'р. Аксу –ж/д. ст. Матай ',
  'nameEn': 'r. Aksu - zh/d st. Matai',
  'pk': 14397,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '45.37',
  'lon': '79.93',
  'name': 'р.Сарыкан –г. Сарканд ',
  'nameEn': 'r. Sarykan - g. Sarkand',
  'pk': 14401,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '46.01',
  'lon': '77.21',
  'name': 'р. Каратал –а. Акжар ',
  'nameEn': 'r. Karatal - a. Akzhar',
  'pk': 14413,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '45.22',
  'lon': '77.97',
  'name': 'р. Каратал-г. Уштобе ',
  'nameEn': 'r. Karatal - g. Ushtobe',
  'pk': 14414,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.86',
  'lon': '78.77',
  'name': 'р. Караой - г.Текели ',
  'nameEn': 'r. Karaoi - g. Tekeli',
  'pk': 14419,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.86',
  'lon': '78.79',
  'name': 'р. Шыжын- г.Текели ',
  'nameEn': 'r. Shyzhyn - g. Tekeli',
  'pk': 14421,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.86',
  'lon': '78.79',
  'name': 'р. Текели-г.Текели ',
  'nameEn': 'r. Tekeli - g.Tekeli',
  'pk': 14426,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.67',
  'lon': '78.93',
  'name': 'р. Коксу-с. Коксу ',
  'nameEn': 'r. Koksu - s. Koksu',
  'pk': 14446,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.59',
  'lon': '79.17',
  'name': 'р. Коктал-с. Аралтобе ',
  'nameEn': 'r. Koktal - s.Araltobe',
  'pk': 14452,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.44',
  'lon': '78.36',
  'name': 'р. Быжы –а.Карымсак ',
  'nameEn': 'r. Byzhy - a. Karymsak',
  'pk': 14476,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '44.63',
  'lon': '77.99',
  'name': 'р. Дос – ж/д. ст. Айнабулак ',
  'nameEn': 'r. Dos - zh/d st. Ainabulak',
  'pk': 14489,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '47.24',
  'lon': '81.57',
  'name': 'Р.Уржар – с.Казымбет',
  'nameEn': 'r. Urdzhar - s. Kazymbet',
  'pk': 14506,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '46.37',
  'lon': '82.24',
  'name': 'Р. Эмель – пос. Кызылту',
  'nameEn': 'r. Emel - pos. Kyzyltu',
  'pk': 14559,
  'region': 'KZ-VOS'},
 {'category': 'ГП-1',
  'lat': '45.78',
  'lon': '80.88',
  'name': 'р. Тентек-а.Сапак ',
  'nameEn': 'r. Tengek - a. Sapak',
  'pk': 14560,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '45.98',
  'lon': '80.97',
  'name': 'р. Тентек – уроч. Тонкерис ',
  'nameEn': 'r. Tentek - uroch. Tonkeris',
  'pk': 14561,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '45.79',
  'lon': '80.64',
  'name': 'р. Шынжалы-а. Акжар ',
  'nameEn': 'r. Shynzhaly - a. Akzhar',
  'pk': 14566,
  'region': 'KZ-ALM'},
 {'category': 'ГП-1',
  'lat': '45.06',
  'lon': '78.36',
  'name': 'р. Коктал –пдх.Плодоконсервный',
  'nameEn': 'r. Koktal - pdh.Plodonoservnyi',
  'pk': 14580,
  'region': 'KZ-ALM'},
 {'category': 'ОГП-2',
  'lat': '45.41',
  'lon': '73.69',
  'name': 'Оз. Балкаш – с.Мынарал',
  'nameEn': 'Oz. Balkash - s.Mynaral',
  'pk': 14902,
  'region': 'KZ-ZHA'},
 {'category': 'ОГП-2',
  'lat': '46.12',
  'lon': '73.62',
  'name': 'оз. Балхаш – ж.д.ст. Сарышаган             ',
  'nameEn': 'Oz. Balkhash -zh.d.st. Saryshagan',
  'pk': 14903,
  'region': 'KZ-KAR'},
 {'category': 'ОГП-2',
  'lat': '46.83',
  'lon': '74.97',
  'name': 'оз. Балхаш – г. Балхаш                            ',
  'nameEn': 'Oz. Balkhash - g.Balkhash',
  'pk': 14904,
  'region': 'KZ-KAR'},
 {'category': 'ОГП-1',
  'lat': '46.54',
  'lon': '77.16',
  'name': 'оз. Балхаш – о. Каракум ',
  'nameEn': 'oz. Balkhash - o. Karakum',
  'pk': 14911,
  'region': 'KZ-ALM'},
 {'category': 'ОГП-2',
  'lat': '43.06',
  'lon': '76.99',
  'name': 'Оз.Улькен Алматы – на сев.берегу озера',
  'nameEn': 'oz. Ulken Almaty - na severnom beregu ozera',
  'pk': 14914,
  'region': 'ALMATY'},
 {'category': 'ОГП-2',
  'lat': '46.69',
  'lon': '80.77',
  'name': 'оз. Сасыкколь-а. Сагат ',
  'nameEn': 'oz. Sasykkol - a. Sagat',
  'pk': 14915,
  'region': 'KZ-ALM'},
 {'category': 'ОГП-2',
  'lat': '46.35',
  'lon': '81.29',
  'name': 'оз. Уялы – с. Алаколь ',
  'nameEn': 'oz. Uyaly',
  'pk': 14916,
  'region': 'KZ-ALM'},
 {'category': 'ОГП-2',
  'lat': '45.96',
  'lon': '81.57',
  'name': 'оз. Алаколь  - с. Акшы ',
  'nameEn': 'oz. Alakol - s. Akshi',
  'pk': 14917,
  'region': 'KZ-ALM'},
 {'category': 'ОГП-2',
  'lat': '45.59',
  'lon': '82.17',
  'name': 'оз. Жаланашколь – ж/д.ст. Жаланашколь ',
  'nameEn': 'oz. Zhalanashkol - zh/d st. Zhalanashkol',
  'pk': 14920,
  'region': 'KZ-ALM'},
 {'category': 'ОГП-2',
  'lat': '43.89',
  'lon': '77.10',
  'name': 'Вдхр. Капшагайское – г. Капшагай',
  'nameEn': 'vdhr. Pachagayskoe - g. Kapchagai',
  'pk': 14921,
  'region': 'ALMATY'},
 {'category': 'ОГП-2',
  'lat': '43.84',
  'lon': '77.85',
  'name': 'Вдхр. Капшагайское –   МС Карашокы',
  'nameEn': 'vdhr. Kapchagaiskoe - MC Karashoky ',
  'pk': 14922,
  'region': 'ALMATY'},
 {'category': 'ГП-1',
  'lat': '43.39',
  'lon': '73.87',
  'name': 'Р. Шу – с. Ташуткуль ',
  'nameEn': 'r. Shu - s. Tashutkul',
  'pk': 15125,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '44.83',
  'lon': '71.14',
  'name': 'Р. Шу (Б. Арна) – с. Уланбель',
  'nameEn': 'r. Shu (B. Arna) -s. Ulanbel',
  'pk': 15134,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '43.12',
  'lon': '73.80',
  'name': 'Р.Сарыкау – (на границе с Кыргызстаном)',
  'nameEn': 'r.Sarykau – (na granitse s. Kyrgyzstanom)',
  'pk': 15208,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '43.18',
  'lon': '74.06',
  'name': 'Р. Аксу – с. Аксу  ',
  'nameEn': 'r. Aksu - s. Aksu',
  'pk': 15213,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '43.21',
  'lon': '74.02',
  'name': 'р. Карабалта –а.Аксу (а. Баласагун)',
  'nameEn': 'r. Karabalta –a.Aksu (a. Balasagun)',
  'pk': 15220,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '43.38',
  'lon': '73.60',
  'name': 'Р. Курагаты – ж.д.ст. Аспара',
  'nameEn': 'r. Kuragaty -zh.d.st. Aspara',
  'pk': 15223,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.77',
  'lon': '73.23',
  'name': 'Р. Мерке – зим. Улбутуй',
  'nameEn': 'r. Merke - zim. Ulbutui',
  'pk': 15233,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.77',
  'lon': '73.23',
  'name': 'Кан. ГЭС – зимовье Улбутуй',
  'nameEn': 'Kan. GES - zimovye Ulbutui',
  'pk': 15235,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '44.83',
  'lon': '71.14',
  'name': 'Р. Шу (М. Арна) – с. Уланбель',
  'nameEn': 'r. Shu (M. Arna) -s. Ulanbel',
  'pk': 15245,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.82',
  'lon': '71.54',
  'name': 'р. Талас – а. Жасоркен ',
  'nameEn': 'r. Talas – a. Zhasorken',
  'pk': 15264,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.81',
  'lon': '71.53',
  'name': 'р. Талас. протока – а. Жасоркен',
  'nameEn': 'r. Talas. protoka – a. Zhasorken',
  'pk': 15266,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-2',
  'lat': '42.68',
  'lon': '71.21',
  'name': 'Р. Асса – ж.д. ст. Маймак',
  'nameEn': 'r. Assa - zh.d.st. Maimak',
  'pk': 15309,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.67',
  'lon': '70.82',
  'name': 'Р. Терс – с.Нурлыкент',
  'nameEn': 'r. Ters - s.Nurlykent',
  'pk': 15314,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.65',
  'lon': '70.67',
  'name': 'Р.Шокпак – с.Журумбай',
  'nameEn': 'r. Shokpak – s. Zhurumbay',
  'pk': 15324,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.92',
  'lon': '70.64',
  'name': 'р. Бериккара – у выхода из гор',
  'nameEn': 'r. Berikkara – u vykhoda iz gor',
  'pk': 15342,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '43.18',
  'lon': '70.43',
  'name': 'Р. Тамды – г.Каратау ',
  'nameEn': 'r. Tamdy - g. Karatau',
  'pk': 15347,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '43.29',
  'lon': '74.18',
  'name': 'Р. Шу – с. Кайнар',
  'nameEn': 'r. Shu - s. Kainar',
  'pk': 15368,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.85',
  'lon': '71.47',
  'name': 'Р. Талас – п. Солнечный',
  'nameEn': 'r. Talas – p. Solnechnyy',
  'pk': 15396,
  'region': 'KZ-ZHA'},
 {'category': 'ОГП-2',
  'lat': '43.39',
  'lon': '73.88',
  'name': 'Вдхр. Ташуткульское – с. Ташуткуль',
  'nameEn': 'Vdkhr. Tashutkulskoye – s. Tashutkul',
  'pk': 15900,
  'region': 'KZ-ZHA'},
 {'category': 'ОГП-1',
  'lat': '42.99',
  'lon': '70.69',
  'name': 'Оз. Бийлюколь – зона отдыха',
  'nameEn': 'Oz. Biylyukol – zona otdykha',
  'pk': 15961,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '41.27',
  'lon': '67.95',
  'name': 'р. Сырдарья – н. б. Шардаринского вдхр.',
  'nameEn': 'r. Syrdarya – n. b. Shardarinskogo vdkhr.',
  'pk': 16031,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-2',
  'lat': '42.14',
  'lon': '68.14',
  'name': 'р. Сырдарья – аул Байыркум',
  'nameEn': 'r. Syrdarya - aul Bayyrkum',
  'pk': 16033,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '43.22',
  'lon': '67.70',
  'name': 'р. Сырдарья – уч. Коктюбе',
  'nameEn': 'r. Syrdarya – uch. Koktyube',
  'pk': 16035,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '44.02',
  'lon': '67.02',
  'name': 'р. Сырдарья – ж.-д. ст. Томенарык',
  'nameEn': 'r. Syrdarya – zh.d. st. Tomenaryk',
  'pk': 16037,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '44.63',
  'lon': '65.91',
  'name': 'р. Сырдарья – раз. Керкелмес',
  'nameEn': 'r. Syrdarya - raz. Kerkelmes',
  'pk': 16039,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '44.99',
  'lon': '65.26',
  'name': 'р. Сырдарья – ж.-д.ст Караозек',
  'nameEn': 'r. Syrdarya – zh.d.st Karaozek',
  'pk': 16042,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '45.47',
  'lon': '64.08',
  'name': 'р. Сырдарья - пгт Жосалы',
  'nameEn': 'r. Syrdarya - pgt. Zhosaly',
  'pk': 16044,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '45.74',
  'lon': '62.13',
  'name': 'р. Сырдарья – г. Казалы',
  'nameEn': 'r. Syrdarya – g. Kazaly',
  'pk': 16047,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '45.00',
  'lon': '65.26',
  'name': 'р. Сырдарья. проток Караозек –ж.-д. ст. Караозек ',
  'nameEn': 'r. Syrdarya. protok Karaozek  zh.d. st. Karaozek',
  'pk': 16052,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '45.48',
  'lon': '64.10',
  'name': 'р. Сырдарья. проток Караозек – пгт Жосалы',
  'nameEn': 'R. Syrdarya. Karaozek protok -pgt. Zhosaly ',
  'pk': 16053,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '43.13',
  'lon': '73.88',
  'name': 'Р. Токташ – с. Жаугаш Батыр',
  'nameEn': 'r. Toktash – s. Zhaugash Batyr',
  'pk': 16246,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '41.74',
  'lon': '69.40',
  'name': 'р. Келес – аул Казыгурт',
  'nameEn': 'r. Keles - aul Kazygurt',
  'pk': 16307,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '41.02',
  'lon': '68.62',
  'name': 'р. Келес - устье',
  'nameEn': 'r. Keles - ustye',
  'pk': 16317,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.55',
  'lon': '70.17',
  'name': 'р. Арысь – аул Жаскешу',
  'nameEn': 'r. Arys - aul Zhaskeshu',
  'pk': 16319,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.45',
  'lon': '68.85',
  'name': 'р. Арысь – ж.д.-ст. Арысь',
  'nameEn': 'r. Arys – zh.d.-st. Arys',
  'pk': 16326,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.78',
  'lon': '68.35',
  'name': 'р. Арысь – аул Шаульдер',
  'nameEn': 'r. Arys - aul Shaulder',
  'pk': 16327,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.42',
  'lon': '70.54',
  'name': 'р. Жабаглысу – аул Жабаглы',
  'nameEn': 'r. Zhabaglysu -aul  Zhabagly ',
  'pk': 16328,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.50',
  'lon': '69.96',
  'name': 'р. Машат – аул Кершетас',
  'nameEn': 'r. Mashat - aul Kershetas',
  'pk': 16340,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.36',
  'lon': '70.00',
  'name': 'р. Аксу – аул Саркырама',
  'nameEn': 'r. Aksu - aul  Sarkyram',
  'pk': 16350,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.55',
  'lon': '69.65',
  'name': 'р. Аксу – аул Колкент',
  'nameEn': 'r. Aksu – aul Kolkent',
  'pk': 16353,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.76',
  'lon': '70.27',
  'name': 'р.Боролдай – с.Васильевка ',
  'nameEn': 'r. Borolday – s.Vasilyevka',
  'pk': 16358,
  'region': 'KZ-ZHA'},
 {'category': 'ГП-1',
  'lat': '42.79',
  'lon': '69.68',
  'name': 'р. Боролдай –аул Боролдай',
  'nameEn': 'r. Boralday – aul Boraldai',
  'pk': 16363,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.34',
  'lon': '69.49',
  'name': 'р. Бадам – аул Кызылжар ',
  'nameEn': 'r. Badam - aul Kyzylzhar',
  'pk': 16374,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.49',
  'lon': '69.09',
  'name': 'р. Бадам – аул Караспан',
  'nameEn': 'r. Badam -aul  Karaspan',
  'pk': 16375,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.23',
  'lon': '70.15',
  'name': 'р. Сайрамсу – аул Тасарык',
  'nameEn': 'r. Sairamsu - aul Tasaryk',
  'pk': 16390,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.26',
  'lon': '70.43',
  'name': 'р. Болдыбрек – у кордона Госзаповедника',
  'nameEn': 'r. Baldyberek – u kordona Goszapovednika',
  'pk': 16395,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.80',
  'lon': '69.20',
  'name': 'р. Бугунь – аул Екпенды',
  'nameEn': 'r. Bugun - aul Ekpendy',
  'pk': 16401,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '43.05',
  'lon': '69.86',
  'name': 'р. Каттабугунь – аул Жарыкбас',
  'nameEn': 'r. Kattabugun - aul Zharykbas',
  'pk': 16404,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '43.16',
  'lon': '69.57',
  'name': 'р. Шаян – в3.3 км ниже устья р. Акбет',
  'nameEn': 'r. Shayan – v 3.3 km nizhe ustya r. Akbet',
  'pk': 16411,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '43.20',
  'lon': '69.38',
  'name': 'р. Аристанды – аул Алгабас',
  'nameEn': 'r. Aristandy -  aul Algabas',
  'pk': 16414,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '43.52',
  'lon': '68.57',
  'name': 'р. Карашик – аул Хантаги',
  'nameEn': 'r. Karashik – aul Khantagi',
  'pk': 16437,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '43.68',
  'lon': '68.03',
  'name': 'р. Ашилган – аул Майдантал',
  'nameEn': 'r. Ashilgan – aul Maydantal',
  'pk': 16474,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '41.00',
  'lon': '68.66',
  'name': 'р. Сырдарья – выше устья р. Келес',
  'nameEn': "r. Syrdarya – vyshe ust'ya r. Keles",
  'pk': 16497,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.59',
  'lon': '69.36',
  'name': 'р.  Шубарсу – аул Шубар',
  'nameEn': 'r. Shubars - aul Shubar',
  'pk': 16499,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '42.66',
  'lon': '70.21',
  'name': 'р. Кокбулак – аул Пистели',
  'nameEn': 'r. Kokbulak – aul Pisteli',
  'pk': 16557,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '40.64',
  'lon': '68.60',
  'name': 'Канал Достык – аул. Шугыла',
  'nameEn': 'Kanal Dostyk - aul. Shugyla',
  'pk': 16620,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '44.76',
  'lon': '65.53',
  'name': 'р. Сырдарья – пгт. Тасбугет',
  'nameEn': 'r. Syrdarya – pgt. Tasbuget',
  'pk': 16659,
  'region': 'KZ-KZY'},
 {'category': 'ГП-1',
  'lat': '46.03',
  'lon': '61.05',
  'name': 'р. Сырдарья – с. Каратерень',
  'nameEn': 'r. Syrdarya – s. Karateren',
  'pk': 16676,
  'region': 'KZ-KZY'},
 {'category': 'ОГП-1',
  'lat': '41.25',
  'lon': '67.97',
  'name': 'Шардаринское вдхр. – г. Шардара',
  'nameEn': 'Shardarinskoe vdhr. - g. Shardara',
  'pk': 16910,
  'region': 'KZ-YUZ'},
 {'category': 'ГП-1',
  'lat': '49.91',
  'lon': '48.22',
  'name': 'Р. Малый Узень – с. Кошанколь',
  'nameEn': 'r. Malyy Uzen – s. Koshankol',
  'pk': 19009,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '49.63',
  'lon': '48.87',
  'name': 'Р.Мал.Узень –с.Бостандык',
  'nameEn': 'r.Mal.Uzen–s.Bostandyk',
  'pk': 19010,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '47.02',
  'lon': '51.82',
  'name': 'р. Урал. протока Яик –  с.Еркинкала',
  'nameEn': 'r. Ural. protoka Zhayik - s. Erkinkala',
  'pk': 19012,
  'region': 'KZ-ATY'},
 {'category': 'ГП-1',
  'lat': '50.08',
  'lon': '48.85',
  'name': 'Р. Бол. Узень – с. Кайынды ',
  'nameEn': 'r. Bol. Uzen - s. Kaiyndy',
  'pk': 19021,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '49.66',
  'lon': '49.47',
  'name': 'Р. Бол. Узень – с. Жалпактал',
  'nameEn': 'r. Bol. Uzen -s. Zhalpaktal',
  'pk': 19022,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '50.87',
  'lon': '49.65',
  'name': 'Р. Чижа 2-я – с. Чижа-2',
  'nameEn': 'R. Chizha 2-ya – s. Chizha-2',
  'pk': 19033,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '50.94',
  'lon': '49.96',
  'name': 'Р. Чижа 1-я – с. Чижа-1',
  'nameEn': 'R. Chizha 1-ya – s. Chizha-1',
  'pk': 19034,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-3',
  'lat': '51.18',
  'lon': '51.38',
  'name': 'Р. Урал – г. Уральск',
  'nameEn': 'R. Ural – g. Uralsk',
  'pk': 19071,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '50.86',
  'lon': '51.14',
  'name': 'Р. Урал – с. Кушум',
  'nameEn': 'R. Ural – s. Kushum',
  'pk': 19072,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '51.44',
  'lon': '52.23',
  'name': 'Р. Урал –  пос. Январцево',
  'nameEn': 'r. Ural – pos. Yanvartsevo',
  'pk': 19073,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '49.02',
  'lon': '51.85',
  'name': 'Р. Урал –  с. Тайпак',
  'nameEn': 'r. Ural – s. Taypak',
  'pk': 19075,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '50.87',
  'lon': '51.14',
  'name': 'кан. Кушум – с. Кушум',
  'nameEn': 'kan. Kushum – s. Kushum',
  'pk': 19083,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '49.48',
  'lon': '58.52',
  'name': 'Р.Шийли-с.Кумсай',
  'nameEn': 'r. Shiili - s. Kumsai',
  'pk': 19130,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.13',
  'lon': '59.09',
  'name': 'Р.Орь-с.Бугетсай',
  'nameEn': "r. Or' - s. Bugetsai",
  'pk': 19132,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.87',
  'lon': '56.70',
  'name': 'Р.Урта-Буртя-пос.Дмитриевка',
  'nameEn': 'r. Urti-Burtya - pos. Dmitrievka',
  'pk': 19180,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.31',
  'lon': '57.23',
  'name': 'Р.Илек-г.Актобе',
  'nameEn': 'r.Ilek - g. Aktobe',
  'pk': 19195,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.80',
  'lon': '56.26',
  'name': 'Р.Илек-пос.Целинное',
  'nameEn': 'r. Ilek - pos. Tselinnoe',
  'pk': 19196,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '51.43',
  'lon': '51.53',
  'name': 'Р. Шаган – с. Чувашинское',
  'nameEn': 'R. Shagan – s. Chuvashinskoye',
  'pk': 19198,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '51.12',
  'lon': '54.07',
  'name': 'Р. Илек – с. Чилик',
  'nameEn': 'r. Ilek - s. Chilik',
  'pk': 19201,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '50.32',
  'lon': '57.31',
  'name': 'Р.Карагала-с.Каргалинское',
  'nameEn': 'r. Karagala - s. Kargalinskoe',
  'pk': 19205,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.73',
  'lon': '57.89',
  'name': 'р.Косистек-с.Косистек',
  'nameEn': 'r. Kosistek - s. Kosistek',
  'pk': 19208,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.37',
  'lon': '57.65',
  'name': 'Р.Актасты-пос.Белогорский',
  'nameEn': 'r. Aktasty - pos.Belgorskiy',
  'pk': 19211,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.16',
  'lon': '55.69',
  'name': 'Р.Большая Кобда-с.Кобда',
  'nameEn': 'r. Bolshaya Kobda - s. Kobda',
  'pk': 19218,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.23',
  'lon': '56.22',
  'name': 'Р.Карахобда-пос.Альпайсай',
  'nameEn': 'r. Karahobda - pos. Alpasai',
  'pk': 19220,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '50.45',
  'lon': '54.14',
  'name': 'Р. Утва – пос. Лубенка',
  'nameEn': 'r. Utva - pos. Lubenka',
  'pk': 19229,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '51.06',
  'lon': '52.95',
  'name': 'Р. Утва – с. Кентубек (с.Григорьевка)',
  'nameEn': "R. Utva – s. Kentubek (s.Grigor'yevka)",
  'pk': 19231,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '51.58',
  'lon': '52.07',
  'name': 'Р. Быковка – с. Чеботарево        ',
  'nameEn': 'r. Bykovka – s. Chebotarevo',
  'pk': 19239,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '51.11',
  'lon': '50.31',
  'name': 'Р. Деркул – пос.Таскала (п. Каменка)',
  'nameEn': 'r. Derkul - pos.Taskala (Kamenka)',
  'pk': 19240,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '51.27',
  'lon': '51.07',
  'name': 'Р. Деркул – пос. Белес',
  'nameEn': 'R. Derkul – pos. Beles',
  'pk': 19243,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '50.66',
  'lon': '52.12',
  'name': 'Р. Куперанкаты – с.Алгабас',
  'nameEn': 'R. Kuperankaty – s.Algabas',
  'pk': 19246,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '50.27',
  'lon': '52.60',
  'name': 'Р. Оленты –  с.Жымпиты (с.Жамбейты)',
  'nameEn': 'r. Olenty - s.Zhimpity (s.Zhambeyty)',
  'pk': 19247,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '50.50',
  'lon': '52.65',
  'name': 'Р. Шидерты –с.Аралтобе ',
  'nameEn': 'r. Shiderty –s. Araltobe',
  'pk': 19249,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '49.87',
  'lon': '53.93',
  'name': 'Р.Калдыгайты – с.Жигерлен',
  'nameEn': 'r. Kaldygayty - s. Zhigerlen',
  'pk': 19254,
  'region': 'KZ-ZAP'},
 {'category': 'ГП-1',
  'lat': '46.61',
  'lon': '48.66',
  'name': 'р. Кигач – с. Шортанбай',
  'nameEn': 'r. Kigach - s. Shortanbay',
  'pk': 19261,
  'region': 'KZ-ATY'},
 {'category': 'ГП-1',
  'lat': '48.55',
  'lon': '57.55',
  'name': 'Р.Эмба-с.Жагабулак',
  'nameEn': 'r. Emba - s. Zhagabulak',
  'pk': 19289,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '48.49',
  'lon': '57.43',
  'name': 'Р.Эмба-пос.Сага',
  'nameEn': 'r. Emba - pos. Saga',
  'pk': 19300,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '49.33',
  'lon': '57.07',
  'name': 'Р.Темир-с.Сагашили',
  'nameEn': 'r. Temir - s. Sagashili',
  'pk': 19301,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '48.92',
  'lon': '57.23',
  'name': 'Р.Темир-пост Ленинский',
  'nameEn': 'r. Temir- post Leninskiy',
  'pk': 19302,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '47.10',
  'lon': '54.37',
  'name': 'Р. Эмба – п.Аккизтогай',
  'nameEn': 'r. Emba - p. Akkiztogay',
  'pk': 19303,
  'region': 'KZ-ATY'},
 {'category': 'ГП-1',
  'lat': '50.87',
  'lon': '54.79',
  'name': 'р.Большая Кобда-с.Когалы',
  'nameEn': 'r. Bolshaya Kobda - s. Kogaly',
  'pk': 19462,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '49.09',
  'lon': '54.67',
  'name': 'Р.Уил-с.Уил',
  'nameEn': 'r. Uil - s. Uil',
  'pk': 19463,
  'region': 'KZ-AKT'},
 {'category': 'ГП-1',
  'lat': '47.68',
  'lon': '51.60',
  'name': 'Р. Урал – пос. Махамбет',
  'nameEn': 'r. Ural - pos. Mahambet',
  'pk': 19801,
  'region': 'KZ-ATY'},
 {'category': 'ГП-1',
  'lat': '47.09',
  'lon': '51.88',
  'name': 'Р. Урал – г. Атырау ',
  'nameEn': 'r. Ural - g. Atyrau',
  'pk': 19802,
  'region': 'KZ-ATY'},
 {'category': 'ГП-1',
  'lat': '47.01',
  'lon': '51.82',
  'name': 'р. Урал – с. Жанаталап',
  'nameEn': 'r. Ural - s. Zhanatalap',
  'pk': 19806,
  'region': 'KZ-ATY'},
 {'category': 'ГП-1',
  'lat': '48.56',
  'lon': '51.74',
  'name': 'р. Урал – пос. Индербор',
  'nameEn': 'r. Ural - pos. Inderbor',
  'pk': 19808,
  'region': 'KZ-ATY'},
 {'category': 'ГП-2',
  'lat': '46.55',
  'lon': '48.76',
  'name': 'Р. Волга. рук.Ахбута. пр.Кигач – с. Котяевка',
  'nameEn': 'r. Volga. ruk. Ahbuta. pr.Kigach - s. Kotyaevka',
  'pk': 77818,
  'region': 'KZ-ATY'},
 {'category': 'ГП-1',
  'lat': '46.60',
  'lon': '49.50',
  'name': 'Р. Волга. прот. Шароновка – с. Ганюшкино',
  'nameEn': 'r. Volga. prot. Sharonovka - s. Ganyushkino',
  'pk': 77819,
  'region': 'KZ-ATY'},
 {'category': 'ОГП-2',
  'lat': '46.54',
  'lon': '60.81',
  'name': 'Аральское море. берег Малого море – п. Тастубек',
  'nameEn': 'Aralskoye more. bereg Malogo more – p. Tastubek',
  'pk': 96009,
  'region': 'KZ-KZY'},
 {'category': 'ОГП-2',
  'lat': '46.11',
  'lon': '60.77',
  'name': 'Малое Аральское море – верх бьеф Кокаральской платины',
  'nameEn': 'Maloye Aralskoye more – verkhniy byef Kokaralskoy plotiny',
  'pk': 96010,
  'region': 'KZ-KZY'},
 {'category': 'МГП-2',
  'lat': '46.37',
  'lon': '49.19',
  'name': 'Каспийское море – Иголкинская банка  ',
  'nameEn': 'Kaspiyskoe more - Igolkinskaya banka',
  'pk': 97046,
  'region': 'KZ-ATY'},
 {'category': 'МГП-2',
  'lat': '47.93',
  'lon': '50.78',
  'name': 'Каспийское море – п. Жамбай',
  'nameEn': 'Kaspiyskoe more - p. Zhambay',
  'pk': 97047,
  'region': 'KZ-ATY'},
 {'category': 'МГП-2',
  'lat': '46.92',
  'lon': '51.69',
  'name': 'Каспийское море – о. Пешной  ',
  'nameEn': 'Kaspiyskoe more - o. Peshnoy',
  'pk': 97048,
  'region': 'KZ-ATY'},
 {'category': 'МГП-2',
  'lat': '45.20',
  'lon': '51.25',
  'name': 'Каспийское море – п.Каламкас',
  'nameEn': 'Kaspiyskoye more – p.Kalamkas',
  'pk': 97057,
  'region': 'KZ-MAN'},
 {'category': 'МГП-3',
  'lat': '44.98',
  'lon': '50.01',
  'name': 'Каспийское море – с. Кугалы',
  'nameEn': 'Kaspiyskoye more – s. Kugaly',
  'pk': 97059,
  'region': 'KZ-MAN'},
 {'category': 'МГП-1',
  'lat': '44.55',
  'lon': '50.25',
  'name': 'Каспийское море – Форт Шевченко',
  'nameEn': 'Kaspiyskoye more – Fort Shevchenko',
  'pk': 97060,
  'region': 'KZ-MAN'},
 {'category': 'МГП-2',
  'lat': '43.60',
  'lon': '51.22',
  'name': 'Каспийское море – г.Актау',
  'nameEn': 'Kaspiyskoye more – g.Aktau',
  'pk': 97061,
  'region': 'KZ-MAN'},
 {'category': 'МГП-2',
  'lat': '43.19',
  'lon': '51.27',
  'name': 'Каспийское море – мыс Песчаный',
  'nameEn': 'Kaspiyskoye more – mys Peschanyy',
  'pk': 97062,
  'region': 'KZ-MAN'},
 {'category': 'МГП-2',
  'lat': '42.79',
  'lon': '52.62',
  'name': 'Каспийское море – п.Фетисово',
  'nameEn': 'Kaspiyskoye more – p.Fetisovo',
  'pk': 97063,
  'region': 'KZ-MAN'},
 {'category': 'МГП-2',
  'lat': '44.22',
  'lon': '50.80',
  'name': 'Каспийское море – с.Саура ',
  'nameEn': 'Kaspiyskoye more – s.Saura',
  'pk': 97064,
  'region': 'KZ-MAN'},
 {'category': 'МГП-2',
  'lat': '43.18',
  'lon': '51.66',
  'name': 'Каспийское море – с.Курык',
  'nameEn': 'Kaspiyskoye more – s.Kuryk',
  'pk': 97090,
  'region': 'KZ-MAN'},
 {'category': 'ОГП-2',
  'lat': '54.91',
  'lon': '69.13',
  'name': 'вдхр.Петропавловское (р.Есиль )-г.Петропавловск',
  'nameEn': 'vdkhr.Petropavlovskoye (r.Yesil )-g.Petropavlovsk',
  'pk': 2300336,
  'region': 'KZ-SEV'},
 {'category': 'ОГП-2',
  'lat': '50.99',
  'lon': '72.12',
  'name': 'Астанинское вдхр. - с. Арнасай',
  'nameEn': 'Astaninskoe vdhr. - s. Arnasai ',
  'pk': 2300407,
  'region': 'KZ-AKM'},
 {'category': 'ОГП-2',
  'lat': '53.01',
  'lon': '70.19',
  'name': 'Оз. Шортан – г. Щучинск',
  'nameEn': 'oz. Shortan - g. Shuchinsk',
  'pk': 2300616,
  'region': 'KZ-AKM'},
 {'category': 'ОГП-2',
  'lat': '53.08',
  'lon': '70.30',
  'name': 'Оз. Бурабай – с. Боровое  ',
  'nameEn': 'Oz. Burabai - s.Borovoe',
  'pk': 2300624,
  'region': 'KZ-AKM'},
 {'category': 'ОГП-2',
  'lat': '52.92',
  'lon': '69.14',
  'name': 'Оз. Зеренды – с. Зеренды ',
  'nameEn': 'oz. Zerendy - s. Zerendy',
  'pk': 2300632,
  'region': 'KZ-AKM'},
 {'category': 'ОГП-2',
  'lat': '53.13',
  'lon': '70.28',
  'name': 'Оз. Улькен Шабакты – с. Боровое',
  'nameEn': 'oz. Ulken Shabakty - s.Borovoe',
  'pk': 2300640,
  'region': 'KZ-AKM'},
 {'category': 'ОГП-2',
  'lat': '47.74',
  'lon': '84.20',
  'name': 'Вдхр. Буктырма – п. Тугыл',
  'nameEn': 'vdhr. Buktyrma - p. Tugyl',
  'pk': 2300711,
  'region': 'KZ-VOS'},
 {'category': 'ОГП-1',
  'lat': '48.22',
  'lon': '83.69',
  'name': 'Вдхр. Буктырма– с. Аксуат',
  'nameEn': 'vdhr. Buktyrma - s. Aksuat',
  'pk': 2300738,
  'region': 'KZ-VOS'},
 {'category': 'ОГП-1',
  'lat': '48.68',
  'lon': '83.49',
  'name': 'Вдхр. Буктырма – п. Куйган',
  'nameEn': 'vdhr. Buktyrma - p.Kuigan',
  'pk': 2300746,
  'region': 'KZ-VOS'},
 {'category': 'ОГП-1',
  'lat': '49.20',
  'lon': '84.34',
  'name': 'Вдхр. Буктырма– пос. Хайрузовка',
  'nameEn': 'vdhr. Buktyrma - pos. Hairuzovka',
  'pk': 2300762,
  'region': 'KZ-VOS'},
 {'category': 'ОГП-1',
  'lat': '49.67',
  'lon': '83.83',
  'name': 'Вдхр. Буктырма – с. Заводинка',
  'nameEn': 'vdhr. Buktyrma - s. Zavodinka',
  'pk': 2300770,
  'region': 'KZ-VOS'},
 {'category': 'ОГП-2',
  'lat': '49.61',
  'lon': '83.50',
  'name': 'Вдхр. Буктырма – с. Селезневка',
  'nameEn': 'vdhr. Buktyrma - s. Seleznevka',
  'pk': 2300789,
  'region': 'KZ-VOS'}
]