# Generated by Django 3.0.4 on 2020-03-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydrostationCategory',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='hydrostation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydrology.HydrostationCategory'),
        ),
    ]
